apiVersion: v1
kind: ServiceAccount
metadata:
  name: opentelemetry-collector-otelcol
  labels:
    app.kubernetes.io/name: otelcol
    app.kubernetes.io/instance: opentelemetry-collector
    app.kubernetes.io/version: "0.82.0"
