apiVersion: v1
kind: Service
metadata:
  name: {{ include "jaeger.fullname" . }}-jaeger
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: "1.45.0"
    app.kubernetes.io/component: all-in-one
spec:
  clusterIP: None
  ports:
    - name: http-query
      port: 16686
      targetPort: 16686
    - name: grpc-query
      port: 16685
      targetPort: 16685
  selector:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: all-in-one
