# Default values for opentelemetry-collector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: otel/opentelemetry-collector-contrib
  tag: 0.82.0
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: opentelemetry-demo-otelcol

service:
  type: ClusterIP
  ports:
    - name: jaeger-compact
      port: 6831
      protocol: UDP
    - name: jaeger-grpc
      port: 14250
      protocol: TCP
    - name: jaeger-thrift
      port: 14268
      protocol: TCP
    - name: metrics
      port: 8888
      protocol: TCP
    - name: otlp
      port: 4317
      protocol: TCP
      appProtocol: grpc
    - name: otlp-http
      port: 4318
      protocol: TCP
    - name: prometheus
      port: 9464
      protocol: TCP
    - name: zipkin
      port: 9411
      protocol: TCP

resources:
  limits:
    memory: 200Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

nodeSelector: {}

tolerations: []

affinity: {}


config:
  relay: |
    # Your relay configuration here
